on:
  push:
    branches:    
      - master
name: iOS Tests
jobs:
  test:
    name: Build
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=macosx']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build && Test
        run: xcodebuild -workspace Sensazonal.xcworkspace -scheme iOS build test
        env: 
         destination: ${{ matrix.destination }}
